version: '3.7'
services:
  app:
    build:
      context: '.'
      dockerfile: 'DockerfileDev'
    volumes:
      - '.:/home/app/src:delegated'
      - 'appnm:/home/app/src/node_modules'
    links:
      - 'db:mongo'
    environment:
      MONGO_MONITOR_MONGO:
      MONGO_MONITOR_DATABASES:
      MONGO_MONITOR_VERBOSE: 1
      LOGR: 'console'
  db:
    image: 'mongo'
    command: 'mongod --smallfiles --quiet'
volumes:
  appnm:
