#!/bin/bash

CMD=$1
shift

if [[ -z "$CMD" ]]; then
  docker-compose up --build
  exit
fi

if [[ "$CMD" == "shell" ]]; then
  docker-compose run --rm app sh
  exit
fi

if [[ "$CMD" == "enter" ]]; then
  docker exec -it $NAME sh
  docker-compose exec app sh
  exit
fi

if [[ "$CMD" == "lint" ]]; then
  docker-compose run --rm app npm run lint
  exit
fi

if [[ "$CMD" == "mongo" ]]; then
  docker-compose exec db mongo test
  exit
fi

if [[ "$CMD" == "npmi" ]]; then
  SERVICE=$2
  PKG=$3
  echo "Installing $PKG inside $SERVICE"
  docker-compose run --rm $SERVICE npm install $PKG
  exit 0
fi


docker-compose $@
